{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b14bbeae-c3bf-401f-b55b-12a6e08307bb",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# ----------------------------\n",
    "# 1️⃣ Load and clean dataset\n",
    "# ----------------------------\n",
    "def load_clean_data(file_path: str) -> pd.DataFrame:\n",
    "    df = pd.read_excel(file_path)\n",
    "    \n",
    "    # Drop useless columns\n",
    "    useless_columns = ['pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',\n",
    "                       'original order', 'Unnamed: 21', 'Unnamed: 22']\n",
    "    df.drop(columns=[c for c in useless_columns if c in df.columns], inplace=True, errors='ignore')\n",
    "    \n",
    "    # Standardize Country, State, Location\n",
    "    for col in ['Country', 'State', 'Location']:\n",
    "        if col in df.columns:\n",
    "            df[col] = df[col].astype(str).str.strip().str.title()\n",
    "    df.replace('Nan', pd.NA, inplace=True)\n",
    "    df[['Country', 'State', 'Location']] = df[['Country', 'State', 'Location']].fillna('Unknown')\n",
    "    \n",
    "    # Clean Activity column\n",
    "    if 'Activity' in df.columns:\n",
    "        df['Activity'] = df['Activity'].astype(str).str.strip().str.title()\n",
    "        df['Activity_Category'] = df['Activity'].apply(categorize_activity)\n",
    "    \n",
    "    # Date and Season\n",
    "    if 'Date' in df.columns:\n",
    "        df['Date'] = pd.to_datetime(df['Date'], errors='coerce')\n",
    "        df['Month'] = df['Date'].dt.month\n",
    "        df['Season'] = df['Month'].apply(get_season)\n",
    "    \n",
    "    # Clean Sex column\n",
    "    if 'Sex' in df.columns:\n",
    "        df['Sex'] = df['Sex'].astype(str).str.strip().str.lower()\n",
    "        df['Sex'] = df['Sex'].replace({'m': 'Male', 'male': 'Male', 'f': 'Female', 'female': 'Female', 'nan': pd.NA})\n",
    "        df['Sex'] = df['Sex'].fillna('Unknown')\n",
    "    \n",
    "    # Clean Age\n",
    "    if 'Age' in df.columns:\n",
    "        df['Age'] = df['Age'].astype(str).str.strip().str.upper()\n",
    "        df['Age'] = df['Age'].replace({\n",
    "            'ADULT': np.nan, 'X': np.nan, 'YOUNG': np.nan, 'TEEN': np.nan,\n",
    "            'NAN': np.nan, '': np.nan, '-': np.nan,\n",
    "            '18 MONTHS': 1.5, '9 MONTHS': 0.75, '8 MONTHS': 0.67\n",
    "        })\n",
    "        df['Age'] = pd.to_numeric(df['Age'], errors='coerce')\n",
    "        df['Age'] = df['Age'].fillna(0).astype(int)\n",
    "    \n",
    "    return df\n",
    "\n",
    "# ----------------------------\n",
    "# 2️⃣ Helper functions\n",
    "# ----------------------------\n",
    "def categorize_activity(act):\n",
    "    act = str(act).lower()\n",
    "    if 'surf' in act: return 'Surfing'\n",
    "    elif 'swim' in act: return 'Swimming'\n",
    "    elif 'wade' in act: return 'Wading'\n",
    "    elif 'snorkel' in act: return 'Snorkeling'\n",
    "    elif 'dive' in act: return 'Diving'\n",
    "    elif 'fish' in act: return 'Fishing'\n",
    "    elif act in ['nan', '']: return 'Unknown'\n",
    "    else: return 'Other'\n",
    "\n",
    "def get_season(month):\n",
    "    if month in [12, 1, 2]: return 'Winter'\n",
    "    elif month in [3, 4, 5]: return 'Spring'\n",
    "    elif month in [6, 7, 8]: return 'Summer'\n",
    "    elif month in [9, 10, 11]: return 'Fall'\n",
    "    else: return 'Unknown'\n",
    "\n",
    "# ----------------------------\n",
    "# 3️⃣ Filter for hypothesis\n",
    "# ----------------------------\n",
    "def filter_hypothesis(df: pd.DataFrame, country='Usa', min_age=12, max_age=20, year_min=1950):\n",
    "    df_hyp = df[\n",
    "        (df['Country'] == country) &\n",
    "        (df['Age'] >= min_age) &\n",
    "        (df['Age'] <= max_age) &\n",
    "        (df['Year'] >= year_min)\n",
    "    ].copy()\n",
    "    return df_hyp\n",
    "\n",
    "# ----------------------------\n",
    "# 4️⃣ Top 5 States & Activities\n",
    "# ----------------------------\n",
    "def top_states(df_hyp: pd.DataFrame, top_n=5):\n",
    "    return df_hyp['State'].value_counts().head(top_n)\n",
    "\n",
    "def top_activities(df_hyp: pd.DataFrame, top_n=5):\n",
    "    return df_hyp['Activity_Category'].value_counts().drop(['Unknown', 'Other'], errors='ignore').head(top_n)\n",
    "\n",
    "# ----------------------------\n",
    "# 5️⃣ Plotting\n",
    "# ----------------------------\n",
    "def plot_bar(data, title, xlabel, ylabel, filename, palette='viridis'):\n",
    "    plt.figure(figsize=(10, 6))\n",
    "    sns.barplot(x=data.index, y=data.values, palette=palette, hue=data.index, dodge=False, legend=False)\n",
    "    plt.title(title)\n",
    "    plt.xlabel(xlabel)\n",
    "    plt.ylabel(ylabel)\n",
    "    plt.xticks(rotation=45, ha='right')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(filename)\n",
    "    plt.close()\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
